# Section 6.1.4 Generate Random Latitudes and Longitudes

In [4]:
# Import the random module.
import random

### For testing, we'll use the randint(), random(), randrange(), and uniform() functions.

In [7]:
random.randint(-90, 90)


-78

In [8]:
random.random()

0.6420273828807409

In [10]:
random_number = random.randint(-90, 89) + random.random()
random_number

39.155524351946006

### Here is a small sample of what it might take to generate ten random floating-point decimal latitudes between –90 and 89.

In [11]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [12]:
latitudes

[-23.94477555559028,
 -3.6956092064188413,
 53.868218012423995,
 -55.67785716076141,
 56.63619116684982,
 -61.76769641115041,
 -28.357967487620726,
 77.8972946450349,
 28.874363439240177,
 85.9992952916276]

In [13]:
random.randrange(-90, 90, step=3)

-42

In [14]:
random.uniform(-90, 90)

13.291074254348018

In [15]:
# Import the NumPy module.
import numpy as np

#### This single line of code generates 50 random numbers with the amount of decimals that we need, all without using loops

In [20]:
np.random.uniform(-90.000, 90.000, size=50)

array([ 31.86318456, -39.78086032,  82.96815115, -82.11175436,
       -72.80361132,  39.29967893, -66.23756842,  85.85240455,
        88.30736716,  28.03241689,  28.43456982,  36.85872107,
       -63.01362538,  15.99947633,  22.73588773,  82.06657281,
        30.70842178,   7.19590125,  -9.08781379,  84.2013411 ,
        87.5552951 , -26.94532965,  86.87799277,  68.31206708,
        56.3567878 ,  31.66635597, -43.9286175 , -16.57216182,
       -68.06212708,  51.76563239, -19.2046535 ,  16.49052805,
        84.02021627,   3.87864716, -61.98993202, -18.26028408,
         3.57755722,  14.70320856,  33.01053174, -42.17921236,
       -55.85038803,  86.28819794,  19.57454293,  30.50066562,
        21.05640831,  88.26187309,  35.11260564,  24.00056598,
        86.08797468, -10.25196281])

### Use of the function %timeit to measure the time it takes to run this command

In [22]:
%timeit np.random.uniform(-90.000, 90.000, size=50)

6.36 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Now, generating 1500 latitudes and 1500 longitudes
#### Remember: Latitud runs north-south and longitude runs east-west

In [25]:
latitudes = np.random.uniform(-90.000, 90.000, size=15000)

In [24]:
latitudes

array([ 36.82084528, -48.77652957, -34.74055569, ...,  66.25615726,
       -19.11650063,   3.52165397])

In [26]:
longitudes = np.random.uniform(0, 365, size=15000)

In [27]:
longitudes

array([323.14264228, 201.23336295,  67.90587579, ...,  78.27305983,
        79.143136  , 117.91071419])