# Section 6.1.4 Generate Random Latitudes and Longitudes

In [1]:
# Import the random module.
import random

### For testing, we'll use the randint(), random(), randrange(), and uniform() functions.

In [2]:
random.randint(-90, 90)


-89

In [3]:
random.random()

0.06984724040727919

In [4]:
random_number = random.randint(-90, 89) + random.random()
random_number

43.62607366010028

### Here is a small sample of what it might take to generate ten random floating-point decimal latitudes between –90 and 89.

In [5]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [6]:
latitudes

[88.20140946081358,
 -62.30587100737965,
 -55.402517703106476,
 88.49621414993649,
 33.60435537791842,
 -22.42878976207946,
 -33.74982402764321,
 -86.99472693458107,
 13.147903638852092,
 71.9160967629415]

In [7]:
random.randrange(-90, 90, step=3)

54

In [8]:
random.uniform(-90, 90)

35.87288849104087

In [9]:
# Import the NumPy module.
import numpy as np

#### This single line of code generates 50 random numbers with the amount of decimals that we need, all without using loops

In [10]:
np.random.uniform(-90.000, 90.000, size=50)

array([  1.33548004, -55.77147343, -89.69182716,  39.05244294,
        64.96497113,   2.17403177,   0.32444612,  48.02698997,
        41.06424052, -67.35594234, -37.78924357, -67.04133018,
        67.53596802, -47.3234972 ,  -2.11491354, -50.57457593,
        34.23978229, -41.27549252, -27.92097627,  20.54270488,
        18.4364814 ,  40.1088148 , -27.87036736, -11.77078897,
       -48.67071235,  42.84711336, -76.6368728 ,  -4.2472696 ,
       -60.26033215,  61.00604707,  41.61099157,  15.33506536,
        89.76706719,  63.46242305,  81.09358652, -29.09157151,
       -66.35066309,  43.61286835, -87.52811252, -22.1059492 ,
       -11.01859804,  -0.15660318,  81.60802712,  86.35364732,
        26.91043388,  -3.23596732, -68.52042177,  27.63169737,
       -58.44484879, -33.41073354])

### Use of the function %timeit to measure the time it takes to run this command

In [11]:
%timeit np.random.uniform(-90.000, 90.000, size=50)

6.15 µs ± 137 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Now, generating 1500 latitudes and 1500 longitudes
#### Remember: Latitud runs north-south and longitude runs east-west

In [12]:
latitudes = np.random.uniform(-90.000, 90.000, size=15000)

In [13]:
latitudes

array([ 39.71922649, -24.81287618,  14.66927363, ..., -77.89110313,
        20.91144959,   4.18050714])

In [14]:
longitudes = np.random.uniform(0, 365, size=15000)

In [15]:
longitudes

array([117.46124019, 304.35530611, 287.77239772, ..., 341.38014162,
       111.67377309,  89.38357836])

# Create Latitude and Longitude Combinations

In [16]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### The zip object packs each pair of lats and lngs having the same index in their respective array into a tuple

In [17]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [18]:
# Use the tuple() function to display the latitude and longitude combinations.
for coordinate in lat_lngs:
    print(coordinate[0], coordinate[1])

38.606881668175475 179.41392339998202
6.577043962133459 -22.582037937029526
-61.54251776749561 79.32714317276714
-44.68618787440305 127.56617599100389
31.005958941113704 160.27295328740217
-66.5961771436128 -113.78564257701578
-80.51010207151646 153.8926840895757
-47.623010896257135 36.68764347531169
-33.87627855139052 110.20896972273266
-76.40979980110843 -58.74446476228913
6.600272064187138 -7.429429931172535
-48.24239865893268 -56.3980281790531
84.72071756790982 -15.595380456161791
28.681799344843483 -14.541827039206254
-7.037976452065024 -148.19330847374238
42.53441134158848 -17.80100058617373
61.13254465829098 20.61920639763173
61.14328410322193 13.234354289443388
-56.52166601157717 75.73524115630488
-47.9695262455016 108.7166782829363
-88.22304485769396 134.31396644114335
13.045192545744413 -23.196550906906936
-20.6881960521399 4.954074365810442
43.186256403512914 -166.5860499732631
-58.837861229709745 67.56714195771363
11.913329825599632 11.95832720007607
88.65756579072149 89.77

31.993810797705578 -148.05676029489356
-72.02069509683105 71.36147180762725
-63.16025003589478 69.314764167339
7.467510737600975 -77.94262820796686
-86.9153516664408 -156.9777299079608
-55.69619816282596 27.072121049789047
83.90384074947121 -16.442781310801735
-1.6080415054071011 -37.766531514921326
-68.90109840132399 -86.85275389683636
-31.012954772272252 138.51588314923453
21.97715149873855 124.43628951403457
11.022521342583687 20.807864794734854
-36.351101412062604 -173.53228475478235
-63.952575744175576 158.81951323344396
-5.576467492470655 119.82841761468052
18.94013837798211 86.41831006717655
67.87030694712317 -11.446170895881977
-8.107213000915579 -6.838496783540251
-33.68820755372126 -79.40749730463246
27.918313826361285 -27.83557153440981
-34.55777764578084 41.162819806892486
20.181190184734362 -101.54847770499248
-25.117645966382227 98.09317905714079
-17.61927099048272 -23.596371841990134
36.856385679299024 80.66967291515488
36.657813778220174 87.76761526939208
80.58575501371

### Now that we have our ordered pairs of latitudes and longitudes in a list, we can iterate through the list of tuples and find the nearest city to those coordinates.

# Section 6.1.5 Generate Random World Cities

## Use the citipy module to determine city based on latitude and longitude.

In [19]:
from citipy import citipy
citipy --ver

NameError: name 'ver' is not defined

# Create a set of random latitude and longitude combinations.

In [ ]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
coordinates = zip(lats, lngs)
# print(coordinates)

for coordinate in coordinates:
    print(coordinate[0], coordinate[1])

# Use the tuple() function to display the latitude and longitude combinations.

In [ ]:
# Use the tuple() function to display the latitude and longitude combinations.
for coordinate in coordinates:
    print(citipy.nearest_city(coordinate[0], coordinate[1]).city_name,
          citipy.nearest_city(coordinate[0], coordinate[1]).country_code)

# Create a list for holding the cities

In [ ]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name,
    citipy.nearest_city(coordinate[0], coordinate[1]).country_code

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

In [ ]:
cities

In [ ]:
city

# Section 6.2.1 Understanding APIs

In [20]:
# import module
from geopy.geocoders import Nominatim
  
# initialize Nominatim API
geolocator = Nominatim(user_agent="geoapiExercises")
  
  
# Latitude & Longitude input
Latitude = "25.594095"
Longitude = "85.137566"
  
location = geolocator.reverse(Latitude+","+Longitude)
  
address = location.raw['address']
  
# traverse the data
city = address.get('city', '')
state = address.get('state', '')
country = address.get('country', '')
code = address.get('country_code')
zipcode = address.get('postcode')
print('City : ', city)
print('State : ', state)
print('Country : ', country)
print('Zip Code : ', zipcode)

ModuleNotFoundError: No module named 'geopy'