# Section 6.1.4 Generate Random Latitudes and Longitudes

In [4]:
# Import the random module.
import random

### For testing, we'll use the randint(), random(), randrange(), and uniform() functions.

In [7]:
random.randint(-90, 90)


-78

In [8]:
random.random()

0.6420273828807409

In [10]:
random_number = random.randint(-90, 89) + random.random()
random_number

39.155524351946006

### Here is a small sample of what it might take to generate ten random floating-point decimal latitudes between –90 and 89.

In [11]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [12]:
latitudes

[-23.94477555559028,
 -3.6956092064188413,
 53.868218012423995,
 -55.67785716076141,
 56.63619116684982,
 -61.76769641115041,
 -28.357967487620726,
 77.8972946450349,
 28.874363439240177,
 85.9992952916276]

In [13]:
random.randrange(-90, 90, step=3)

-42

In [14]:
random.uniform(-90, 90)

13.291074254348018

In [15]:
# Import the NumPy module.
import numpy as np

#### This single line of code generates 50 random numbers with the amount of decimals that we need, all without using loops

In [20]:
np.random.uniform(-90.000, 90.000, size=50)

array([ 31.86318456, -39.78086032,  82.96815115, -82.11175436,
       -72.80361132,  39.29967893, -66.23756842,  85.85240455,
        88.30736716,  28.03241689,  28.43456982,  36.85872107,
       -63.01362538,  15.99947633,  22.73588773,  82.06657281,
        30.70842178,   7.19590125,  -9.08781379,  84.2013411 ,
        87.5552951 , -26.94532965,  86.87799277,  68.31206708,
        56.3567878 ,  31.66635597, -43.9286175 , -16.57216182,
       -68.06212708,  51.76563239, -19.2046535 ,  16.49052805,
        84.02021627,   3.87864716, -61.98993202, -18.26028408,
         3.57755722,  14.70320856,  33.01053174, -42.17921236,
       -55.85038803,  86.28819794,  19.57454293,  30.50066562,
        21.05640831,  88.26187309,  35.11260564,  24.00056598,
        86.08797468, -10.25196281])

### Use of the function %timeit to measure the time it takes to run this command

In [22]:
%timeit np.random.uniform(-90.000, 90.000, size=50)

6.36 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Now, generating 1500 latitudes and 1500 longitudes
#### Remember: Latitud runs north-south and longitude runs east-west

In [25]:
latitudes = np.random.uniform(-90.000, 90.000, size=15000)

In [24]:
latitudes

array([ 36.82084528, -48.77652957, -34.74055569, ...,  66.25615726,
       -19.11650063,   3.52165397])

In [26]:
longitudes = np.random.uniform(0, 365, size=15000)

In [27]:
longitudes

array([323.14264228, 201.23336295,  67.90587579, ...,  78.27305983,
        79.143136  , 117.91071419])

# 

In [1]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### The zip object packs each pair of lats and lngs having the same index in their respective array into a tuple

In [2]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [9]:
# Use the tuple() function to display the latitude and longitude combinations.
for coordinate in lat_lngs:
    print(coordinate[0], coordinate[1])

33.11901138127901 -133.1366539939229
57.1632459650578 -64.69756414076429
88.13013403113209 -2.541084845889145
53.56875490409806 122.32653997236383
37.00656946746467 84.1768511481219
56.05353259004474 53.958794727332474
-40.808064121195926 147.49259454524923
-68.40134475754093 -119.19711469757723
-54.62959934201263 -26.040098289647915
29.70453076613404 -66.9180021585153
6.355474274512233 -10.128867361382731
-53.68217937629728 176.94554216704006
-88.66730162143749 164.0491612367739
53.784438820354694 85.92056871843397
53.029796044421346 -28.7806618498212
52.083105974780636 -14.563454232329747
-88.03387259642274 -111.01733056826707
-79.45084364519786 134.33088459667653
-55.290702913657064 -125.9967621222101
-32.58851496946577 47.75693594155524
82.532692635118 40.798460650612355
-39.69688685759842 40.91669973548497
2.0927643937619678 -61.01302117651717
56.20308236469225 86.76438983618402
-58.560268766445326 57.77644193655041
-87.14900826067256 -13.282158227938226
73.84845372206948 -4.02072

-53.54834016697096 -90.84799886266322
71.82440711830245 106.36829115427503
-36.15300735799221 -34.083699130787494
84.18117208759773 -18.831880940061524
-70.49944027586366 179.54476344851724
67.01619654361662 -25.468482160468653
7.524593634152438 -111.58439489105217
4.737202043766274 107.86121830065235
-88.74400137964662 161.1456389284778
-41.81472439246185 -39.68978606127024
-64.87241581239554 -148.19104375981306
35.6746038695335 -179.2043785479807
-82.29145906108299 19.642110534811565
45.14762013418536 -27.67196764858545
-56.4639463825788 -174.41133055251316
37.538274408761424 41.48543993011785
85.29411368749024 68.45099299762524
58.967383474391596 89.68629970015388
83.36024395614976 -154.67762867885565
22.378706114669072 -86.59413880463606
-51.34127854745913 -12.1359678578699
53.68784689377898 92.66325886113026
-26.077823961984713 149.118108175933
-18.16283120482389 -48.54147383250748
-73.9995977067779 -124.96754528840452
-24.818738523861782 31.493401184359527
12.411896850562869 -126

### Now that we have our ordered pairs of latitudes and longitudes in a list, we can iterate through the list of tuples and find the nearest city to those coordinates.